version: "3.8"

services:

  postgres:
    image: postgres 
    container_name: postgres
    ports:
      - 5432:5432
    restart: always
    # volumes:
    #   - ./backend/db_data/:/var/lib/postgresql/data
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DATABASE

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - $MACHINE_ADMINER_PORT:$ADMINER_PORT
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      - postgres
  
  server:
    build: ./backend/
    container_name: server
    restart: always
    ports:
      - 3000:3000
    command: sh ./docker-entrypoint.sh
    environment:
      DATABASE_URL: $DATABASE_URL
      SERVER_PORT: $SERVER_PORT
    volumes:
      - ./backend/:/usr/app/
    depends_on:
      - postgres